// Pre-warmed Zero-API Static JSON Snapshots for Famous Builders on IndieForest
// Guarantees <50ms instant sprout on landing hero with 0 risk of GitHub 429 rate-limits.

import { GitHubIslandProfile } from "./github";
import { GrowthTier } from "@/types/game";
import { WEST_EMERALD_SLOTS } from "./gamification";

export const CURATED_FAMOUS_BUILDERS: Record<string, GitHubIslandProfile> = {
  levelsio: {
    username: "levelsio",
    avatarUrl: "https://github.com/levelsio.png",
    totalCommits: 342,
    streakDays: 48,
    level: 18,
    xp: 2800,
    pinecones: 420,
    activeReposCount: 4,
    lastActiveDate: new Date().toISOString(),
    recentCommits: [
      {
        id: "c-lev-1",
        repo: "levelsio/photoai-engine",
        message: "feat: ultra-fast flux lora rendering pipeline",
        date: new Date().toISOString(),
        author: "levelsio",
      },
      {
        id: "c-lev-2",
        repo: "levelsio/nomadlist",
        message: "perf: cache city weather and nomad scores",
        date: new Date(Date.now() - 86400000).toISOString(),
        author: "levelsio",
      },
    ],
    trees: [
      {
        id: "tree-levels-1",
        name: "PhotoAI",
        type: "shipping",
        commits: 128,
        activeDays: 34,
        mrr: 0,
        tier: "majestic" as GrowthTier,
        gridX: WEST_EMERALD_SLOTS[0][0],
        gridZ: WEST_EMERALD_SLOTS[0][1],
        plantedAt: new Date(Date.now() - 86400000 * 90).toISOString(),
        isDemo: true,
      },
      {
        id: "tree-levels-2",
        name: "NomadList",
        type: "shipping",
        commits: 84,
        activeDays: 28,
        mrr: 0,
        tier: "majestic" as GrowthTier,
        gridX: WEST_EMERALD_SLOTS[1][0],
        gridZ: WEST_EMERALD_SLOTS[1][1],
        plantedAt: new Date(Date.now() - 86400000 * 60).toISOString(),
        isDemo: true,
      },
      {
        id: "tree-levels-3",
        name: "RemoteOK",
        type: "shipping",
        commits: 46,
        activeDays: 14,
        mrr: 0,
        tier: "mature" as GrowthTier,
        gridX: WEST_EMERALD_SLOTS[2][0],
        gridZ: WEST_EMERALD_SLOTS[2][1],
        plantedAt: new Date(Date.now() - 86400000 * 30).toISOString(),
        isDemo: true,
      },
      {
        id: "tree-levels-4",
        name: "InteriorAI",
        type: "shipping",
        commits: 18,
        activeDays: 6,
        mrr: 0,
        tier: "young" as GrowthTier,
        gridX: WEST_EMERALD_SLOTS[3][0],
        gridZ: WEST_EMERALD_SLOTS[3][1],
        plantedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
        isDemo: true,
      },
    ],
  },

  shadcn: {
    username: "shadcn",
    avatarUrl: "https://github.com/shadcn.png",
    totalCommits: 512,
    streakDays: 64,
    level: 24,
    xp: 5400,
    pinecones: 890,
    activeReposCount: 3,
    lastActiveDate: new Date().toISOString(),
    recentCommits: [
      {
        id: "c-shad-1",
        repo: "shadcn-ui/ui",
        message: "feat: add double-bezel porcelain component primitives",
        date: new Date().toISOString(),
        author: "shadcn",
      },
    ],
    trees: [
      {
        id: "tree-shad-1",
        name: "shadcn/ui",
        type: "shipping",
        commits: 240,
        activeDays: 45,
        mrr: 0,
        tier: "majestic" as GrowthTier,
        gridX: WEST_EMERALD_SLOTS[0][0],
        gridZ: WEST_EMERALD_SLOTS[0][1],
        plantedAt: new Date(Date.now() - 86400000 * 120).toISOString(),
        isDemo: true,
      },
      {
        id: "tree-shad-2",
        name: "taxonomy",
        type: "shipping",
        commits: 54,
        activeDays: 18,
        mrr: 0,
        tier: "mature" as GrowthTier,
        gridX: WEST_EMERALD_SLOTS[1][0],
        gridZ: WEST_EMERALD_SLOTS[1][1],
        plantedAt: new Date(Date.now() - 86400000 * 45).toISOString(),
        isDemo: true,
      },
      {
        id: "tree-shad-3",
        name: "next-template",
        type: "shipping",
        commits: 22,
        activeDays: 8,
        mrr: 0,
        tier: "young" as GrowthTier,
        gridX: WEST_EMERALD_SLOTS[2][0],
        gridZ: WEST_EMERALD_SLOTS[2][1],
        plantedAt: new Date(Date.now() - 86400000 * 15).toISOString(),
        isDemo: true,
      },
    ],
  },

  antfu: {
    username: "antfu",
    avatarUrl: "https://github.com/antfu.png",
    totalCommits: 890,
    streakDays: 120,
    level: 32,
    xp: 9200,
    pinecones: 1420,
    activeReposCount: 4,
    lastActiveDate: new Date().toISOString(),
    recentCommits: [
      {
        id: "c-antfu-1",
        repo: "antfu/unocss",
        message: "feat: zero-runtime CSS engine optimizations",
        date: new Date().toISOString(),
        author: "antfu",
      },
    ],
    trees: [
      {
        id: "tree-antfu-1",
        name: "unocss",
        type: "shipping",
        commits: 180,
        activeDays: 50,
        mrr: 0,
        tier: "majestic" as GrowthTier,
        gridX: WEST_EMERALD_SLOTS[0][0],
        gridZ: WEST_EMERALD_SLOTS[0][1],
        plantedAt: new Date(Date.now() - 86400000 * 90).toISOString(),
        isDemo: true,
      },
      {
        id: "tree-antfu-2",
        name: "vitest",
        type: "shipping",
        commits: 140,
        activeDays: 40,
        mrr: 0,
        tier: "majestic" as GrowthTier,
        gridX: WEST_EMERALD_SLOTS[1][0],
        gridZ: WEST_EMERALD_SLOTS[1][1],
        plantedAt: new Date(Date.now() - 86400000 * 75).toISOString(),
        isDemo: true,
      },
      {
        id: "tree-antfu-3",
        name: "vueuse",
        type: "shipping",
        commits: 65,
        activeDays: 22,
        mrr: 0,
        tier: "mature" as GrowthTier,
        gridX: WEST_EMERALD_SLOTS[2][0],
        gridZ: WEST_EMERALD_SLOTS[2][1],
        plantedAt: new Date(Date.now() - 86400000 * 40).toISOString(),
        isDemo: true,
      },
    ],
  },

  marclou: {
    username: "marclou",
    avatarUrl: "https://github.com/marclou.png",
    totalCommits: 220,
    streakDays: 30,
    level: 14,
    xp: 2100,
    pinecones: 380,
    activeReposCount: 3,
    lastActiveDate: new Date().toISOString(),
    recentCommits: [
      {
        id: "c-marc-1",
        repo: "marclou/shipfast",
        message: "feat: Next.js 16 + React 19 boilerplate template",
        date: new Date().toISOString(),
        author: "marclou",
      },
    ],
    trees: [
      {
        id: "tree-marc-1",
        name: "ShipFast",
        type: "shipping",
        commits: 95,
        activeDays: 28,
        mrr: 0,
        tier: "majestic" as GrowthTier,
        gridX: WEST_EMERALD_SLOTS[0][0],
        gridZ: WEST_EMERALD_SLOTS[0][1],
        plantedAt: new Date(Date.now() - 86400000 * 60).toISOString(),
        isDemo: true,
      },
      {
        id: "tree-marc-2",
        name: "LaunchFast",
        type: "shipping",
        commits: 40,
        activeDays: 12,
        mrr: 0,
        tier: "mature" as GrowthTier,
        gridX: WEST_EMERALD_SLOTS[1][0],
        gridZ: WEST_EMERALD_SLOTS[1][1],
        plantedAt: new Date(Date.now() - 86400000 * 30).toISOString(),
        isDemo: true,
      },
      {
        id: "tree-marc-3",
        name: "ByeDispute",
        type: "shipping",
        commits: 15,
        activeDays: 5,
        mrr: 0,
        tier: "young" as GrowthTier,
        gridX: WEST_EMERALD_SLOTS[2][0],
        gridZ: WEST_EMERALD_SLOTS[2][1],
        plantedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
        isDemo: true,
      },
    ],
  },
};

export const FAMOUS_BUILDER_HANDLES = ["levelsio", "shadcn", "antfu", "marclou"] as const;
